### ISSUE TITLE
yocto_cutrace compile errors

### ISSUE THREAD

**Issue by ib00** [xelatihy/yocto-gl#1348]
Cool project!

I am getting a lot of compile errors in yocto_cutrace. Most are related to vector functions:

/tmp/yocto-gl/libs/yocto/yocto_cutrace.cu(173): error: no instance of constructor "yocto::vec2f::vec2f" matches the argument list
            argument types are: (int, int)

/tmp/yocto-gl/libs/yocto/yocto_cutrace.cu(376): error: namespace "std" has no member "swap"

I am compiling with gcc 11.1 and CUDA 11.5 on linux.

**Comment by xelatihy** [comment]
That sounds strange, but I do not have a version of CUDA for Linux, nor it is enabled in CI, so I cannot verify this. I'll see if I can get CI to work for Linux and CUDA.

**Comment by xelatihy** [comment]
It seems I was not able to find an easy way to install CUDA/Optix in CI reliably. I'll keep this around a bit, but may soon drop it if there is no way to get CI to work in this case.

**Comment by ib00** [comment]
I am happy to investigate myself.

With your latest `commit,` I am now getting different errors than before (with g++ 11.1)

Consolidate compiler generated dependencies of target yocto_cutrace_device_ptx
[ 62%] Building CUDA object libs/yocto/CMakeFiles/yocto_cutrace_device_ptx.dir/yocto_cutrace.ptx

/tmp/yocto-gl/libs/yocto/yocto_math.h(81): error: duplicate specifier in declaration
/tmp/yocto-gl/libs/yocto/yocto_math.h(82): error: duplicate specifier in declaration

(and hundreds of these)

If I try to compile with clang (13.0), I only get one error:

/tmp/yocto-gl/libs/yocto/yocto_math.h:1036:10: error: no member named 'isfinite' in the global namespace; did you mean simply 'isfinite'?
  return ::isfinite(a);  // no namespace for CUDA
         ^~~~~~~~~~
         isfinite

If I change 

::isfinite(a) to isfinite(a)

everything compiles with clang.



`

**Comment by xelatihy** [comment]
Couple of things:

1. The `isfinite` is very hairy since it is possibly a macro in `math.h`; that I do not know what is the right thing beside the fact that it should work with `std::infinite` from `cmath`, but it does not on windows. I'll relook. As you put it, it may go in infinite loop.

2. The multiple definitions depends on a hack I did to avoid code duplication, while preserving the code clean; example at line 60 in `yocto_math.h`; a possible fix may be to remove of the `inline` keywords only for gcc.

Sorry for the issue, but I do not have a Linux machine handy.

**Comment by ib00** [comment]
Thanks for looking into this. I appreciate it.

I've had lots of problems with 'isfinite' before as well.

**Comment by xelatihy** [comment]
Closing this since I cannot reproduce without a machine.
